wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CRNN
dataset:
  desc: null
  value: MusicSpectograms
epochs:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685212710.919438
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.15.0
      8:
      - 1
      - 5
